// kasa/src/components/Gallery/Gallery.jsx
import React, {useState} from "react";
import right from "../../assets/images/rightArrow.svg";
import left from "../../assets/images/leftArrow.svg";

export default function Gallery({ slides }) {
    const [current, setCurrent] = useState(0); // je défini l'index du premier element du tableau  "current" à 0
    const length = slides.length;

    const nextSlide = () => {
        setCurrent(current === length - 1 ? 0 : current + 1); // on part au premier slide quand on arrive au dernier
    };
    const prevSlide = () => {
        setCurrent(current === 0 ? length - 1 : current - 1); // on part au dernier slide quand est au premier
    }
    return (
        <section id='gallery-container'>
            {length > 1 && (
                <img
                    src={left} // j'affiche la fleche si et seulement s'il y a 2 images ou plus (length > 1)
                    alt="gauche"
                    className='leftArrow'
                    onClick={prevSlide}
                />
            )}
            {length > 1 && (
                <img
                    src={right}
                    alt="droite"
                    className='rightArrow'
                    onClick={nextSlide}
                />
            )}
            {slides.map((slide, index) => (
                <div
                    key={index}
                    className={
                        current === index
                            ? "slider bl-msk wh-msk active-anim"
                            : "slider bl-msk wh-msk"
                    }
                >
                    {index === current && <img src={slide} alt="appartement à louer" /> }
                    {index === current && (
                        <span className="slider__number">
                            {current + 1}/{length}
                        </span>
                    )}

                </div>
            ))}
            {/*Gallery*/}
        </section>
    )
}

// kasa-agular/src/app/components/gallery/gallery.component.ts
import {Component, Input, OnInit} from '@angular/core';
@Component({
  selector: 'app-gallery',
  templateUrl: './gallery.component.html',
  styleUrls: ['./gallery.component.scss']
})
export class GalleryComponent implements OnInit {

  @Input() slides: any;
  public length: any;
  public current = 0;
  constructor() { }

  ngOnInit(): void {
    this.length = this.slides.length;
    console.log(this.slides);
  }

  // tslint:disable-next-line:typedef
  nextSlide() {
    // on part au premier slide quand on arrive au dernier
    this.current = this.current === this.length - 1 ? 0 : this.current + 1;
  }
  // tslint:disable-next-line:typedef
  prevSlide() {
    // on part au dernier slide quand est au premier
    this.current = this.current === 0 ? this.length - 1 : this.current - 1;
  }

}


<section id="gallery-container">
<!--  // j'affiche la fleche si et seulement s'il y a 2 images ou plus (length > 1)-->
  <img *ngIf="length > 1"
       src="../../assets/images/leftArrow.svg"
        alt="gauche"
        class='leftArrow'
       (click)="prevSlide()"
  />
  <img *ngIf="length > 1 "
    src="../../../assets/images/rightArrow.svg"
    alt="droite"
    class='rightArrow'
    (click)="nextSlide()"
  />
  <div *ngFor="let slide of slides; let index = index"
    key="index"
    [ngClass]="{
         'slider bl-msk wh-msk active-anim': current === index,
          'slider bl-msk wh-msk': current != index
    }"
  >
    <img *ngIf="index === current" [src]="slide" alt="appartement à louer" />
    <span *ngIf="index === current" class="slider__number">
  {{current +1}}/{{length}}
  </span>

  </div>
<!--  {/*Gallery*/}-->
</section>
