// kasa/src/pages/Home/Home.jsx
import React, {useEffect, useState} from "react";
import Card from "../../components/Card/Card";
import axios from "axios";
import Banner from "../../components/Banner/Banner";
import datas from '../../datas/Data.json'
import { Link } from "react-router-dom";

export default function Home () {
    const [data, setData] = useState([]);

    useEffect(() => {
        // console.log(data);
        // console.log(datas);
        setData(datas);
    }, []);
    console.log(data);
    return (
        <>
            <Banner />
            <div className="cards-container">
                {data.map((appart, id) =>(
                    <div className="card_logement" key={id}>
                        {/*<div> { console.log(appart)}</div>*/}
                        <Link to={`/logement/${appart.id}`} className="link_card_logement" >
                            <Card cover={appart.cover} title={appart.title} />
                        </Link>
                    </div>
                ))}
            </div>
        </>
    )
}

// kasa-agular/src/app/pages/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { data } from '../../datas/Data';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  public data: any;
  constructor() { }

  ngOnInit(): void {
    this.data = data;
  }

}

<p>home works!</p>

<div>
<app-banner></app-banner>
<div class="cards-container">
  <div class="card_logement" *ngFor="let appart of data; let id = index">
    <a href="./logement/{{appart.id}}" class="link_card_logement">
      <app-card [coverCard]="appart.cover" [titleCard]="appart.title"></app-card>
    </a>
  </div>
<!--  {data.map((appart, id) =>(-->
<!--                    <div className="card_logement" key={id}>-->
<!--  <Link to={`/logement/${appart.id}`} className="link_card_logement" >-->
<!--                            <Card cover={appart.cover} title={appart.title} />-->
<!--                        </Link>-->
<!--                    </div>-->
<!--                ))}-->
</div>
</div>
