// kasa/src/components/Card/Card.jsx
import React from "react";

export default function Card({ cover, title }) {
    return (
        <article className="card-logement">
            <img src={cover} alt="location" />
            <div className="card-logement__layer">
                <p className="card-logement__title">{title}</p>
            </div>
        </article>
    )
}

// kasa-agular/src/app/components/card/card.component.ts
import {Component, Input, OnInit} from '@angular/core';

@Component({
  selector: 'app-card',
  templateUrl: './card.component.html',
  styleUrls: ['./card.component.scss']
})
export class CardComponent implements OnInit {

  @Input() coverCard: any;
  @Input() titleCard: any;
  constructor() { }

  ngOnInit(): void {
  }

}

<p>card works!</p>

<article class="card-logement">
  <img [src]="coverCard" alt="location" />
  <div class="card-logement__layer">
    <p class="card-logement__title">{{titleCard}}</p>
  </div>
</article>
