// kasa/src/components/Rate/Rate.jsx
import React from "react";
import fullStar from '../../assets/images/star-rate.svg';
import emptyStar from '../../assets/images/emptyStar.svg';

export default function Rate({ score }) {
    const stars = [1, 2, 3, 4, 5];
    return (
        <div className='rate-comp'>
            {stars.map((level) => score
                >= level
                ? (
                    <img
                        key={level.toString()}
                        className='star'
                        src={fullStar}
                        alt="étoile de notation"
                    />
                )
                : ( // affichage conditionnel des étoiles de notation (score), pleine ou vide selon le score passé en props
                    <img
                        key={level.toString()}
                        className='star'
                        src={emptyStar}
                        alt="étoile de notation"
                    />
                )
            )}
            {/*Rate*/}
        </div>
    )
}

// kasa-agular/src/app/components/rate/rate.component.ts
import {Component, Input, OnInit} from '@angular/core';

@Component({
  selector: 'app-rate',
  templateUrl: './rate.component.html',
  styleUrls: ['./rate.component.scss']
})
export class RateComponent implements OnInit {

  @Input() score: any;
  public stars = [1, 2, 3, 4, 5];
  constructor() { }

  ngOnInit(): void {
  }

}


<div class='rate-comp'>
  <section *ngFor="let level of stars">
    <img *ngIf="score >= level"
      key="level.toString()"
      class='star'
      src="../../../assets/images/star-rate.svg"
      alt="étoile de notation"
    />
    <img *ngIf="score < level"
      key="level.toString()"
      class='star'
      src="../../../assets/images/emptyStar.svg"
      alt="étoile de notation"
    />
<!--    {/*Rate*/}-->
  </section>
</div>
