// kasa-agular/src/app/components/collapse/collapse.component.ts
import {Component, Input, OnInit} from '@angular/core';

@Component({
  selector: 'app-collapse',
  templateUrl: './collapse.component.html',
  styleUrls: ['./collapse.component.scss']
})
export class CollapseComponent implements OnInit {

  @Input() key: any;
  @Input() aboutTitle: any;
  @Input() aboutText: any;
  @Input() aboutStyle: any;
  @Input() dataCollapse: any;

  public toggle = false;
   public heightEl: any;
   public arrayaboutText: any[] = [];
   refHeight: any;

  constructor() { }

  ngOnInit(): void {
    console.log(this.aboutStyle);
    // console.log(this.dataCollapse);
    this.setHeightEl();
    // this.arrayaboutText = this.aboutText.split(1, ',');
    console.log(this.arrayaboutText);
    console.log(this.aboutText);
  }

  // tslint:disable-next-line:typedef
  toggleState() {
    this.setToggle();
    // this.refHeight = this.toggle;
  }
  // tslint:disable-next-line:typedef
  setToggle() {
    this.toggle = !this.toggle;
  }
  // tslint:disable-next-line:typedef
  setHeightEl() {
    // console.log(this.refHeight);
    // @ts-ignore
    // this.heightEl = `${this.refHeight.current.scrollHeight}px`;
    // this.heightEl = this.refHeight;
    // console.log(this.heightEl);
  }

}

<!--<p>collapse works!</p>-->

<div class="collapse {{aboutStyle}}">
      <div
        (click)="toggleState()"
        class="collapse__visible"
      >
        <h2>{{aboutTitle}}</h2>
        <img
        [ngClass]="toggle ? 'chevron-roted' : 'chevron'"
        src="../../../assets/images/chevron.svg"
        alt="chevron"
        />
      </div>
      <div
          [ngClass]="toggle ? 'collapse__toggle-animated' : 'collapse__toggle'"
          [style]="{ height: toggle ? heightEl : '0px'}"
        >

        <p *ngIf="toggle" aria-hidden="true">
        {{aboutText}}
        </p>

        <p *ngIf="!toggle" >
          {{aboutText}}
        </p>
      </div>
<!--      <div-->
<!--          [ngClass]="toggle ? 'collapse__toggle animated' : 'collapse__toggle'"-->
<!--          [style]="{ height: toggle ? heightEl : '0px'}"-->
<!--        >-->

<!--        <p *ngIf="toggle" aria-hidden="true">-->
<!--        {{aboutText}}-->
<!--        </p>-->

<!--        <p *ngIf="!toggle" >-->
<!--          {{aboutText}}-->
<!--        </p>-->
<!--      </div>-->
</div>

// kasa/src/components/Collapse/Collapse.jsx
import React, {useEffect, useRef, useState} from "react";
import chevron from '../../assets/images/chevron.svg'

export default function Collapse(props) {
    const [toggle, setToggle] = useState(false); // toggle === intérupteur
    const [heightEl, setHeightEl] = useState(); // initialisation de la hauteur du collapse

    const toggleState = () => {
        console.log(toggle);
        // la fonction de modification de l'intérupteur est donc chargé ici de modifier son status (true / false) au click
        setToggle(!toggle);
    };
    // console.log(toggle);

    const refHeight = useRef(); // conservation de la valeur du collaps déplié

    useEffect(() => {
        console.log(refHeight);
        setHeightEl(`${refHeight.current.scrollHeight}px`);
    }, []); // définition de la hauteur du collapse déplié a sa première ouverture et conservation de cette hauteur dans refHeight

    return (
        <div className={`collapse ${props.aboutStyle}`}>
            {/*<div>*/}
            {/*    {console.log(props)}*/}
            {/*</div>*/}
            <div
                onClick={toggleState}
                className="collapse__visible"
            >
                <h2>{props.aboutTitle}</h2>
                <img
                    className={toggle ? 'chevron roted' : 'chevron'}
                    src={chevron}
                    alt="chevron"
                />
            </div>
            <div
                className={toggle ? 'collapse__toggle animated' : 'collapse__toggle'}
                ref={refHeight}
                style={{ height: toggle ? `${heightEl}` : '0px'}}
            >
                <p aria-hidden={toggle ? 'true' : 'false'}>
                    {props.aboutText}
                </p>

            </div>
            {/*COLLAPSE*/}
        </div>
    );
}
