// kasa-agular/src/app/components/host/host.component.ts
import {Component, Input, OnInit} from '@angular/core';

@Component({
  selector: 'app-host',
  templateUrl: './host.component.html',
  styleUrls: ['./host.component.scss']
})
export class HostComponent implements OnInit {

  @Input() hostName: any;
  @Input() hostPicture: any;
  @Input() hostId: any;
  constructor() { }

  ngOnInit(): void {
  }

}


<div class='host-comp'>
  <div class="host-name">{{hostName}}</div>
  <div class="hostPicture">
    <img [src]="hostPicture" [alt]="hostId" />
  </div>
<!--  {/*Host*/}-->
</div>

// kasa/src/components/Host/Host.jsx
import React from "react";

export default function Host(props) {
    return (
        <div className='host-comp'>
            <div className="host-name">{props.hostname}</div>
            <div className="hostPicture">
                <img src={props.hostPicture} alt={props.id} />
            </div>
            {/*Host*/}
        </div>
    );
}
