// kasa/src/pages/FicheLogement/FicheLogement.jsx
import React, {useEffect, useState} from "react";
import axios from "axios";
import {useNavigate, useParams} from "react-router-dom";
import datas from "../../datas/Data.json"
import Gallery from "../../components/Gallery/Gallery";
import Tag from "../../components/Tag/Tag";
import Host from "../../components/Host/Host";
import Rate from "../../components/Rate/Rate";
import Collapse from "../../components/Collapse/Collapse";

export default function FicheLogement () {
    const params = useParams();
    const navigate = useNavigate();

    const [pickedAppart, sePickedAppart] = useState();
    useEffect(() => {
        const getData = async () => {

            const data = datas;
            // const resp = await axios.get("/logements.json");
            console.log(data);
            const piked = data.find(({ id }) => id === params.id);
            data.map(() => sePickedAppart(piked));
            if (piked === undefined) {
                navigate("/404", { state : { message: "Impossible de récupérer les données"}});
            }

        };
        getData().then(r => console.log(r));
    }, []);

    const slidePics = pickedAppart && pickedAppart.pictures;
    const tags = pickedAppart && pickedAppart.tags;
    const equipments = pickedAppart && pickedAppart.equipments;

    const equip = pickedAppart && equipments.map((item, index) => (
        <li
            key={index}
            className='equipList'
        >
            {item}
        </li>
    ))
    return (
        pickedAppart && (
            <div key={params.id} className='fiche-container'>
                <Gallery slides={slidePics} />
                {/*FICHE LOGEMENT*/}
                <section className='hostInfo-container'>
                    <div className='title-tags-container'>
                        <div className='title-container redFont'>
                            <h1>{pickedAppart.title}</h1>
                            <h3>{pickedAppart.location}</h3>
                        </div>
                        <div className='tags-container'>
                            {tags.map(tag =>(
                                <Tag key={tag} tag={tag} />
                            ))}
                        </div>
                    </div>
                    <div className='rate-host-container'>
                        <div className='host-container redFont'>
                            <Host
                                hostName={pickedAppart.host.name}
                                hostPicture={pickedAppart.host.picture}
                            />
                        </div>
                        <div className='rate-container'>
                            <Rate score={pickedAppart.rating} />
                        </div>
                    </div>
                </section>
                <div className="collapse-fiche-container">
                    <Collapse
                        aboutTitle='Description'
                        aboutText={pickedAppart.description}
                    />
                    <Collapse
                        aboutTitle='Équipements'
                        aboutText={equip}
                    />
                </div>
            </div>
        )
    )
}

// kasa-agular/src/app/pages/fiche-logement/fiche-logement.component.ts
import { Component, OnInit } from '@angular/core';
import { data } from '../../datas/Data';
import {ActivatedRoute, Router} from '@angular/router';

@Component({
  selector: 'app-fiche-logement',
  templateUrl: './fiche-logement.component.html',
  styleUrls: ['./fiche-logement.component.scss']
})
export class FicheLogementComponent implements OnInit {

  public aboutTitle = 'Équipements';
  public pickedAppart: any;
  public piked: any;
  public dataArray: any;
  public params: any;
  public equip: any;
  public slidePics: any;
  public tags: any;
  public equipments: any;
  public description = 'Description';
  public equipements = 'Équipements';
  constructor(
    private activatedRoute: ActivatedRoute,
    private route: Router
  ) { }

  ngOnInit(): void {
    this.params = this.activatedRoute.snapshot.params;
    this.getData();
    console.log(this.params);
    console.log(this.slidePics);
    console.log(this.pickedAppart);
    this.getData();
    this.initParams();
  }
  // tslint:disable-next-line:typedef
  sePickedAppart(elt: any) {
    this.pickedAppart = elt;
  }
  // tslint:disable-next-line:typedef
  getData() {
    this.dataArray = data;
    console.log(this.dataArray);
    this.piked = this.dataArray.find((elt: any) => elt.id === this.params.id);
    console.log(this.piked);
    this.dataArray.map(() => this.sePickedAppart(this.piked));
  }

  // tslint:disable-next-line:typedef
  initParams() {
    this.slidePics = this.pickedAppart.pictures;
    this.tags = this.pickedAppart.tags;
    this.equipments = this.pickedAppart.equipments;

    this.equip = this.equipments.forEach((item: any, index: any) => (
      `<li
        key=${index}
    class='equipList'
      >
      ${item}
      </li>
      `
    ));
  }
}

<!--<p>fiche-logement works!</p>-->
<section  *ngIf="pickedAppart">
  <div key="params.id" class="fiche-container">
    <app-gallery [slides]="slidePics" > </app-gallery>
    <!--    {/*FICHE LOGEMENT*/}-->
    <section class='hostInfo-container'>
      <div class='title-tags-container'>
        <div class='title-container redFont'>
          <h1>{{pickedAppart.title}}</h1>
          <h3>{{pickedAppart.location}}</h3>
        </div>
        <div class="tags-container" *ngFor="let tag of tags">
          <app-tag [keyFich]="tag" [tag]="tag" > </app-tag>
        </div>
      </div>
      <div class='rate-host-container'>
        <div class='host-container redFont'>
          <app-host
            [hostName]="pickedAppart.host.name"
            [hostPicture]="pickedAppart.host.picture"
            [hostId]="pickedAppart.host.id"
          ></app-host>
        </div>
        <div class='rate-container'>
          <app-rate [score]="pickedAppart.rating" ></app-rate>
        </div>
      </div>
    </section>
    <div class="collapse-fiche-container">
      <app-collapse
        [aboutTitle]="description"
        [aboutText]="pickedAppart.description"
      > </app-collapse>
      <app-collapse
        [aboutTitle]="equipements"
        [aboutText]="equip"
      ></app-collapse>
    </div>
  </div>
</section>
